/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ConnectToRouteImport } from './routes/connect-to'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WheelConnectionIdRouteImport } from './routes/wheel.$connectionId'
import { Route as SettingsConnectionIdRouteImport } from './routes/settings.$connectionId'

const ConnectToRoute = ConnectToRouteImport.update({
  id: '/connect-to',
  path: '/connect-to',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WheelConnectionIdRoute = WheelConnectionIdRouteImport.update({
  id: '/wheel/$connectionId',
  path: '/wheel/$connectionId',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsConnectionIdRoute = SettingsConnectionIdRouteImport.update({
  id: '/settings/$connectionId',
  path: '/settings/$connectionId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/connect-to': typeof ConnectToRoute
  '/settings/$connectionId': typeof SettingsConnectionIdRoute
  '/wheel/$connectionId': typeof WheelConnectionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/connect-to': typeof ConnectToRoute
  '/settings/$connectionId': typeof SettingsConnectionIdRoute
  '/wheel/$connectionId': typeof WheelConnectionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/connect-to': typeof ConnectToRoute
  '/settings/$connectionId': typeof SettingsConnectionIdRoute
  '/wheel/$connectionId': typeof WheelConnectionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/connect-to'
    | '/settings/$connectionId'
    | '/wheel/$connectionId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/connect-to' | '/settings/$connectionId' | '/wheel/$connectionId'
  id:
    | '__root__'
    | '/'
    | '/connect-to'
    | '/settings/$connectionId'
    | '/wheel/$connectionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConnectToRoute: typeof ConnectToRoute
  SettingsConnectionIdRoute: typeof SettingsConnectionIdRoute
  WheelConnectionIdRoute: typeof WheelConnectionIdRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/connect-to': {
      id: '/connect-to'
      path: '/connect-to'
      fullPath: '/connect-to'
      preLoaderRoute: typeof ConnectToRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wheel/$connectionId': {
      id: '/wheel/$connectionId'
      path: '/wheel/$connectionId'
      fullPath: '/wheel/$connectionId'
      preLoaderRoute: typeof WheelConnectionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/$connectionId': {
      id: '/settings/$connectionId'
      path: '/settings/$connectionId'
      fullPath: '/settings/$connectionId'
      preLoaderRoute: typeof SettingsConnectionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConnectToRoute: ConnectToRoute,
  SettingsConnectionIdRoute: SettingsConnectionIdRoute,
  WheelConnectionIdRoute: WheelConnectionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
